"""
AI Conversion Uplift Modeling - Professional Evaluation Suite
Evaluates the massive 13,979,592 row XGBoost models against our held-out test set.
Highlights Portfolio Skills: Calibration, ROC-AUC, Class Imbalance Trade-offs.
"""
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import roc_auc_score, brier_score_loss

def main():
    print("📈 INITIATING PROFESSIONAL EVALUATION SUITE")
    
    # 1. Load the Held-Out Test Data (Our 20% Sandbox Test Data)
    print("[1/4] Loading perfectly clean Test Data for Evaluation...")
    X_test = pd.read_csv("data/X_test.csv")
    y_test = pd.read_csv("data/y_test.csv")
    
    treatment_flags = X_test['treatment']
    features = X_test.drop(columns=['treatment'])
    y_true = y_test['conversion']
    
    # 2. Load the Fully Trained 14M-Row Brains
    print("[2/4] Loading the massive 13.9M-Row AI Brains from disk...")
    model_treat = xgb.XGBClassifier()
    model_treat.load_model("models/treatment_model.xgb")
    
    model_ctrl = xgb.XGBClassifier()
    model_ctrl.load_model("models/control_model.xgb")
    
    # 3. Generate Predictions
    print("[3/4] Generating Mathematical Probabilities...")
    prob_treat = model_treat.predict_proba(features)[:, 1]
    prob_ctrl = model_ctrl.predict_proba(features)[:, 1]
    uplift_scores = prob_treat - prob_ctrl
    
    # 4. Professional Metrics (The Portfolio Flex)
    print("\n" + "="*60)
    print(" 📊 PROFESSIONAL METRICS (CALIBRATION & BIAS)")
    print("="*60)
    
    # METRIC 1: Brier Score
    # Because conversion rates are incredibly low (0.14%), predicting exactly 0 or 1 is stupid.
    # Brier Score measures how perfectly accurate the *Decimal Probability* is.
    brier_treat = brier_score_loss(y_true[treatment_flags == 1], prob_treat[treatment_flags == 1])
    brier_ctrl = brier_score_loss(y_true[treatment_flags == 0], prob_ctrl[treatment_flags == 0])
    
    print(f"1. Brier Score Calibration (Treatment): {brier_treat:.5f}")
    print(f"   Brier Score Calibration (Control):   {brier_ctrl:.5f}")
    print("   -> (A score near 0.000 means the probabilities are perfectly calibrated to reality.)")
    
    # METRIC 2: ROC-AUC 
    # Can the model correctly rank a highly-likely buyer above a highly-unlikely buyer?
    roc_treat = roc_auc_score(y_true[treatment_flags == 1], prob_treat[treatment_flags == 1])
    roc_ctrl = roc_auc_score(y_true[treatment_flags == 0], prob_ctrl[treatment_flags == 0])
    print(f"\n2. ROC-AUC Discrimination (Treatment): {roc_treat:.4f}")
    print(f"   ROC-AUC Discrimination (Control):   {roc_ctrl:.4f}")
    print("   -> (Any score over 0.50 proves the AI is fundamentally mathematically intelligent.)")
    
    # METRIC 3: Trade-off Analysis (Thresholding)
    print("\n--- 3. Class Imbalance & Bias Analysis ---")
    print("Because 99.8% of users NEVER buy, the AI is heavily statistically biased toward predicting very small decimals.")
    print("Maximum predicted Uplift Score generated by the 13.9M model: +" + f"{(np.max(uplift_scores)*100):.3f}%")
    print("Minimum predicted Uplift Score generated by the 13.9M model: " + f"{(np.min(uplift_scores)*100):.3f}%")
    
    # Thresholding logic (0.001 is 0.10% uplift)
    persuadables = np.sum(uplift_scores > 0.001) 
    sleeping_dogs = np.sum(uplift_scores < -0.001)
    
    print(f"\nIf the CEO sets the Business ROI Cutoff at +0.10% Uplift:")
    print(f"We will specifically TARGET {persuadables:,} massive Persuadables.")
    print(f"We will completely BLACKLIST {sleeping_dogs:,} Sleeping Dogs who hate ads.")
    print(f"We will IGNORE all remaining customers because they are Sure Things or Lost Causes.")
    
    print("\n✅ PROFESSIONAL EVALUATION SUITE COMPLETED.")

if __name__ == "__main__":
    main()
